site_name: "Advanced Methods in Applied Statistics 2025"
repo_name: jakob1379/AMAS2025
repo_url: https://github.com/jakob1379/AMAS2025
site_url: 'https://jakob1379.github.io/AMAS2025/'

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    # KU Black for the header and navigation
    # A dark theme option with KU Red as the primary highlight
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"      
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: red
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.tabs.link
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.prune
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
  favicon: assets/Ku-ucph-logo-svg.svg
  logo: assets/Ku-ucph-logo-svg.svg

nav:
  - Home: index.md
  - Classes: classes.md

plugins:
  - search
  - glightbox
  - mike

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  homepage: https://nbi.ku.dk/
  version:
    provider: mike
    
extra_css:
  - styles/custom.css

